export enum Cargo {
  MEDICO = 'MEDICO',
  ENFERMEIRO = 'ENFERMEIRO',
  AUXILIAR_DE_ENFERMAGEM = 'AUXILIAR_DE_ENFERMAGEM',
  TECNICO_DE_ENFERMAGEM = 'TECNICO_DE_ENFERMAGEM',
  ESTAGIARIO = 'ESTAGIARIO',
}
