export enum CondicaoSaude {
  FEBRE_ALTA = 'FEBRE_ALTA',
  FEBRE = 'FEBRE',
  ESTADO_FEBRIL = 'ESTADO_FEBRIL',
  NORMAL = 'NORMAL',
  HIPOTERMIA = 'HIPOTERMIA',
  TAQUICARDIA = 'TAQUICARDIA',
  BRADICARDIA = 'BRADICARDIA',
  CRISE_HIPERTENSIVA = 'CRISE_HIPERTENSIVA',
  HIPERTENSAO_ESTAGIO_2 = 'HIPERTENSAO_ESTAGIO_2',
  HIPERTENSAO_ESTAGIO_1 = 'HIPERTENSAO_ESTAGIO_1',
  PRE_HIPERTENSAO = 'PRE_HIPERTENSAO',
  HIPOTENSAO = 'HIPOTENSAO',
}
